server:
  port: 8761                    # 指定该Eureka实例的端口
eureka:
  instance:
      hostname: peer2
  client:
    serviceUrl:
      defaultZone: http://peer1:8760/eureka/
spring:
  application:
    name: eurekaserver
