server:
  port: 8760                    # 指定该Eureka实例的端口
eureka:
  instance:
      hostname: peer1
  client:
    serviceUrl:
      defaultZone: http://peer2:8761/eureka/
spring:
  application:
    name: eurekaserver
